# treetop-ofx-test

* Parsing OFX Responses with Treetop

** Version 1xx versus 2xx
The main differences in the two versions:

** Headers
1xx and 2xx uses different headers, which have been removed from the sample
response files, since parsing out the headers is not done by Treetop.  The
main thing we want from the header is the OFX version of the response file,
which are just hardwired in this example.

** Value Fields
1xx uses SGML syntax in which a value-bearing field can be expressed without a
closing tag, like this:

#+begin_example
  <NAME>PERIODONTAL SPECIALIST LEAW
#+end_example

but since the end tag is optional, this should work as well:

#+begin_example
  <NAME>PERIODONTAL SPECIALIST LEAW</NAME>
#+end_example

In version 2xx, only the latter example should be valid.

** Issues with my Treetop Grammars

I have been using the version 1xx grammar for many years successfully, but
there is an issue with it: the grammar does not allow a closing tag on a value
field, even though it is optional.  However, when I add an optional closing
tag, the grammar breaks.  This has not been a problem in the wild since it
appears that almost all financial institutions leave off the closing tag.

Most financial institutions seem to still use the version 1xx syntax, but I
have run across one that uses the v2xx syntax, and I want a grammar that
parses those files was well.
